### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sigorilla** [banditi/mipt_hack_server#2]
Hi there. 

@kyza1994 suggested good list of the ideas. I think we should stick to this list.
- [ ] Add social networks
  - [x] VK
  - [ ] Facebook 
  - [ ] Twitter
  - [ ] Instagram
- [x] Add comments to the events
- [ ] Add organization for the event
- [ ] Add sorting
  - by creator
  - by organization
  - by date
- [ ] Add registration data **Not registration, but in settings**
  - group of the student
  - course
  - gender
- [ ] Create events for only groups, course, departments, etc.
- [ ] Suggest events
  - Take into account my previous visit for suggesting
- [ ] Create events only for user friends
- [ ] Create ban list
- [x] Create rating of the events
- [ ] Periodical events (monthly, weekly, etc.)
- [x] Sandbox for events (save, but not publish)

P.S. thank Egor for this list

**Comment by krokhin** [comment]
- Site should have form: suggest a category or make a category.
- It is necessary to add subscription, kinda wall like in Instagram with new events.
- It can be cool to implement suggestions.
- Verife account using MIPT electronic pass. (?)

**Comment by sigorilla** [comment]
## Language

Так как проект уже приватный, то давайте писать на русскому :smile:

**Comment by sigorilla** [comment]
@Yefim-Krokhin 

Я думаю ввести модераторов, тем более что Джанго поддерживает сразу такую опцию. и тем самым модераторы смогут добавлять категории. Как такая идея? А остальные пользователи смогут только предлагать.

**Comment by krokhin** [comment]
Насчет модера дельно, потому как не админу же сидеть это делать.

**Comment by sigorilla** [comment]
Необходимо также сделать сортировку для категорий как в админке, так и на сайте.
